import Image from "next/image";
import { list } from "@vercel/blob";
export const dynamic = "force-dynamic";
async function getPhotos(){if(!process.env.BLOB_READ_WRITE_TOKEN)return [];try{const {blobs}=await list({prefix:"gallery/"});return blobs.map(b=>({url:b.url,pathname:b.pathname}));}catch{return [];}}
export default async function Home(){const photos=await getPhotos();return <main>
<header className="topbar"><div className="container nav"><a className="brand" href="#start">CHATA <span>POLSKA</span></a><nav><a href="#gazetka">Gazetka</a><a href="#promocje">Promocje</a><a href="#zdjecia">Zdjęcia</a><a href="#sklep">Sklep</a><a href="#kontakt">Kontakt</a></nav></div></header>
<section id="start" className="hero"><div className="container heroGrid"><div><p className="eyebrow">CHATA POLSKA • RAWICZ</p><h1>Twoje codzienne zakupy.<br/><span>Po polsku.</span></h1><p className="lead">Sprawdź aktualną gazetkę, promocje i najważniejsze informacje o sklepie w Rawiczu.</p><div className="actions"><a className="button" href="#gazetka">Zobacz gazetkę</a><a className="textButton" href="#sklep">Jak dojechać ↓</a></div></div><div className="heroCard"><div className="heroBadge">AKTUALNE PROMOCJE</div><div className="heroCardTitle">Zobacz, co<br/>jest w gazetce.</div><div className="heroCardBottom">Oferty • Rawicz</div></div></div></section>
<section id="gazetka" className="section newspaper"><div className="container"><div className="sectionHead"><div><p className="eyebrow">GAZETKA PROMOCYJNA</p><h2>Najnowsza gazetka</h2></div><a className="textButton" href="https://www.chatapolska.pl/" target="_blank" rel="noreferrer">Oficjalna strona Chata Polska ↗</a></div><a className="flyer" href="https://www.chatapolska.pl/" target="_blank" rel="noreferrer"><Image src="/gazetka.svg" alt="Gazetka promocyjna Chata Polska" width={1200} height={1600} priority className="flyerImage"/></a><div className="replaceNote"><strong>Gazetka online</strong><span>Po kliknięciu przejdziesz na oficjalną stronę Chata Polska, gdzie publikowana jest aktualna gazetka.</span></div></div></section>
<section id="promocje" className="section light"><div className="container"><p className="eyebrow">NAJWAŻNIEJSZE INFORMACJE</p><h2>Zakupy blisko domu</h2><div className="cards"><article><span className="number">01</span><b>Świeże produkty</b><p>Warzywa, owoce, pieczywo i produkty na codzienny stół.</p></article><article><span className="number">02</span><b>Regularne promocje</b><p>Aktualne oferty i gazetkę znajdziesz na oficjalnej stronie sieci.</p></article><article><span className="number">03</span><b>Rawicz</b><p>Najważniejsze dane sklepu, telefon i wskazówki dojazdu w jednym miejscu.</p></article></div></div></section>
<section id="zdjecia" className="section"><div className="container"><div className="sectionHead"><div><p className="eyebrow">GALERIA</p><h2>Sklep i okolica</h2></div><p className="muted">Zdjęcia dodane przez właściciela pojawią się tutaj.</p></div>{photos.length?<div className="gallery">{photos.map(photo=><img key={photo.pathname} src={photo.url} alt="Chata Polska Rawicz" loading="lazy"/>)}</div>:<div className="emptyGallery">Galeria jest gotowa. Zdjęcia można dodać z prywatnego panelu.</div>}</div></section>
<section id="sklep" className="section light"><div className="container storeGrid"><div><p className="eyebrow">CHATA POLSKA RAWICZ</p><h2>Znajdź nas<br/>w Rawiczu.</h2><p className="lead">Sklep przy ul. Spokojna, 63-900 Rawicz. Poniżej masz szybkie przejście do mapy i kontaktu.</p><div className="actions"><a className="button" href="https://www.google.com/maps/search/?api=1&query=Chata%20Polska%20Spokojna%2C%2063-900%20Rawicz" target="_blank" rel="noreferrer">Nawiguj do sklepu ↗</a><a className="textButton" href="https://www.chatapolska.pl/sklepy/wielkopolskie/rawicz%2C1379.html" target="_blank" rel="noreferrer">Oficjalne dane sklepu ↗</a></div></div><div id="kontakt" className="contactBox"><p className="boxLabel">KONTAKT</p><h3>Chata Polska</h3><p><strong>Adres</strong><br/>Spokojna<br/>63-900 Rawicz</p><p><strong>Telefon</strong><br/><a href="tel:+48616500360">61 650 03 60</a></p><p><strong>Gazetka</strong><br/><a href="https://www.chatapolska.pl/" target="_blank" rel="noreferrer">chatapolska.pl ↗</a></p></div></div></section>
<footer><div className="container footerInner"><span>© 2026 Chata Polska</span><span>Rawicz • Spokojna</span></div></footer></main>}